export const dataProjectsPage = [
  {
    id: 1,
    title: "Full recipe app",
    desc: "Create Recipe App With ReactJs, axios And More Tooles, Please Check Everything. ",
    img: "/assets/projectsImg/desctop/full-recipe.png",
    mobileImg: "/assets/projectsImg/mobile/full-recipe.png",
    link: "https://full-recipy-app.netlify.app/",
    code: "https://github.com/omarelkamah/Full-Recipe-App",
    buttonColor: "#26272b",
    madeWith: [
      "react",
      "react hooks",
      "axios",
      "react router dom",
      "local storage",
      "styled-components",
      "framer-motion",
      "react-icons",
      "react-splide",
      "spoonacular api",
    ],
  },
  {
    id: 2,
    title: "E-Commerce React App",
    desc: "Create E-commerce App With ReactJs And More Tooles, Please Check Everything. ",
    img: "/assets/projectsImg/desctop/commerce.png",
    mobileImg: "/assets/projectsImg/mobile/commerce.png",
    link: "https://e-commerce-react-hooks-app.netlify.app/",
    code: "https://github.com/omarelkamah/E-Commerce-App-React",
    buttonColor: "teal",
    madeWith: ["react", "react hooks", "react router dom", "styled components"],
  },
  {
    id: 3,
    title: "Cyrptocurency react app",
    desc: "Create Cyrptocurency With ReactJs, axios And More Tooles, Please Check Everything. ",
    img: "/assets/projectsImg/desctop/cyrency.png",
    mobileImg: "/assets/projectsImg/mobile/cyrency.png",
    link: "https://cyrptocurency-react-app.netlify.app/",
    code: "https://github.com/omarelkamah/Cryptocurrency-React-App",
    buttonColor: "#26272b",
    madeWith: [
      "react",
      "react hooks",
      "axios",
      "react router dom",
      "scss",
      "api",
    ],
  },
  {
    id: 4,
    title: "Tesla React App",
    desc: "Create Tesla Clone With ReactJs And More Tooles, Please Check Everything. ",
    img: "/assets/projectsImg/desctop/tesla.png",
    mobileImg: "/assets/projectsImg/mobile/tesla.png",
    link: "https://tesla-react-website.netlify.app/",
    code: "https://github.com/omarelkamah/Tesla-React-App",
    buttonColor: "#252b31",
    madeWith: [
      "react",
      "react hooks",
      "styled components",
      "react router dom",
      "matrial ui",
    ],
  },
  {
    id: 5,
    title: "weather React App",
    desc: "Create weathe With ReactJs, axios And More Tooles, Please Check Everything. ",
    img: "/assets/projectsImg/desctop/weather.png",
    mobileImg: "/assets/projectsImg/mobile/weather.png",
    link: "https://weather-react-app0.netlify.app/",
    code: "https://github.com/omarelkamah/Weather-React-App",
    buttonColor: "#4a434a",
    madeWith: ["react", "react hooks", "axios", "css", "api"],
  },
  {
    id: 6,
    title: "Blog React App",
    desc: "Create Blog App With ReactJs And More Tooles, Please Check Everything. ",
    img: "/assets/projectsImg/desctop/blog.png",
    mobileImg: "/assets/projectsImg/mobile/blog.png",
    link: "https://blog-react-web-app.netlify.app/",
    code: "https://github.com/omarelkamah/Blog_App_React",
    buttonColor: "#438080",
    madeWith: [
      "react",
      "react hooks",
      "react router dom",
      "scss",
      "react router dom",
    ],
  },
  {
    id: 7,
    title: "Agency React App",
    desc: "Create Agency App With ReactJs And More Tooles, Please Check Everything. ",
    img: "/assets/projectsImg/desctop/agency.png",
    mobileImg: "/assets/projectsImg/mobile/agency.png",
    link: "https://agency-react-web-app.netlify.app/",
    code: "https://github.com/omarelkamah/Agency-App-React",
    buttonColor: "#dc143c",
    madeWith: ["react", "react hooks", "react router dom", "styled components"],
  },
  {
    id: 8,
    title: "Cericht React App",
    desc: "Create Cericht App With ReactJs And More Tooles, Please Check Everything. ",
    img: "/assets/projectsImg/desctop/cericht.png",
    mobileImg: "/assets/projectsImg/desctop/cericht.png",
    link: "https://cericht-resturant.netlify.app/",
    code: "https://github.com/omarelkamah/CERICHT-Resturant",
    buttonColor: "#0c0c0c",
    madeWith: ["react", "react hooks", "react router dom", "scss"],
  },
  {
    id: 9,
    title: "Admin Panal React App",
    desc: "Create Admin Panal With ReactJs And More Tooles, Please Check Everything. ",
    img: "/assets/projectsImg/desctop/admin-panal.png",
    mobileImg: "",
    link: "https://admin-panal-react-app.netlify.app/",
    code: "https://github.com/omarelkamah/Admin-Panal-React",
    buttonColor: "#150c8b",
    madeWith: ["react", "react hooks", "react router dom", "scss"],
  },
  {
    id: 10,
    title: "Education.com",
    desc: "Create Education.com With Scss And More Tooles, Please Check Everything. ",
    img: "/assets/projectsImg/desctop/education.png",
    mobileImg: "/assets/projectsImg/mobile/education.png",
    link: "https://omarelkamah.github.io/education/",
    code: "https://github.com/omarelkamah/Education_Sass",
    buttonColor: "#7352ff",
    madeWith: ["html", "html5", "scss", "boptstrap", "javaScript", "jQuery"],
  },
  {
    id: 11,
    title: "Crispy.com",
    desc: "Create Crispy.com With Scss And More Tooles, Please Check Everything. ",
    img: "/assets/projectsImg/desctop/crispy.png",
    mobileImg: "/assets/projectsImg/mobile/crispy.png",
    link: "https://omarelkamah.github.io/Crispy/",
    code: "https://github.com/omarelkamah/Crispy",
    buttonColor: "#f85a40",
    madeWith: ["html", "html5", "scss", "booptstrap", "javaScript", "jQuery"],
  },
  {
    id: 12,
    title: "Test Design",
    desc: "Create Test Design With Puer JavaScript And More Tooles, Please Check Everything. ",
    img: "/assets/projectsImg/desctop/newDesign.png",
    mobileImg: "/assets/projectsImg/mobile/newDesign.png",
    link: "https://omarelkamah.github.io/NewDesign/",
    code: "https://omarelkamah.github.io/Crispy/",
    buttonColor: "#017cff",
    madeWith: [
      "html",
      "html5",
      "css",
      "css3",
      "localStorage",
      "javaScript",
      "jQuery",
    ],
  },
];
